name: Build and Deploy Node App

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: aaleem1993/twnprojectjenkins
  CONTAINER_NAME: twn-app-container
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ubuntu

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Get version from package.json
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t $DOCKER_IMAGE:${{ env.VERSION }} .

    - name: Push Docker Image
      run: docker push $DOCKER_IMAGE:${{ env.VERSION }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
           docker pull $DOCKER_IMAGE:${{ env.VERSION }}
           docker stop $CONTAINER_NAME || true
           docker rm $CONTAINER_NAME || true
           docker run -d --name $CONTAINER_NAME -p 3000:3000 $DOCKER_IMAGE:${{ env.VERSION }}
